source 'https://rubygems.org'

gem 'middleman', '~> 4.2'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-sprockets'
gem 'middleman-deploy', git: 'https://github.com/lewagon/middleman-deploy.git'

# Assets
gem 'font-awesome-sass', '~> 4.2.0'
gem 'bootstrap-sass', '~> 3.3.1'
gem 'jquery-middleman'

